### ISSUE TITLE
nvm doesn't play nicely with nodePath

### ISSUE THREAD

**Issue by mastastealth** [lifeart/ember-language-server#100]
Using `nvm` to manage my node, I ran into an issue where my template linting was not working at all. With @lifeart 's guidance, we narrowed it down to [this block](https://github.com/lifeart/ember-language-server/blob/component-context-info-origin/src/template-linter.ts#L96-L98):
```js
if (!nodePath) {
  return;
}
```
inside the `getLinter` getting hit, which I guess bails on everything else. Commenting this out return the linting in my editor. :clap:

**Comment by lifeart** [comment]
@mastastealth fix should be in UELS 1.4.1 (https://twitter.com/vaier/status/1264120208438034439)
