### ISSUE TITLE
isFixable does not work for ember-template-lint-plugin-tailwindcss

### ISSUE THREAD

**Issue by MichalBryxi** [lifeart/ember-language-server#121]
The problem seems to be that the something fails once there is a linebreak in between opening and closing HTML tag. The problem manifests itself as "no quick fixes available" in vscode.

<img width="663" alt="Screenshot 2020-05-23 at 16 35 20" src="https://user-images.githubusercontent.com/847473/82735933-8a697180-9d1d-11ea-94ff-463f690580ec.png">

- [Affected plugin](https://gitlab.com/michal.bryxi/ember-template-lint-plugin-tailwindcss/blob/c50bccb47d61d446ecdb981c8dec7dc7d2ff311c/lib/rules/class-order.js#L49)
- [Discussion on Discord](https://discordapp.com/channels/480462759797063690/666416704418611233/713780489663807549)
- [PR with a failing test](https://github.com/lifeart/ember-language-server/pull/122)
```js
 FAIL  test/bultin-addons/core/template-linter-test.ts
  ● ProjectTemplateLinter › it return valid result on template with linebreaks

    TypeError: Cannot read property 'type' of undefined

      19 |
      20 |   while (cursor) {
    > 21 |     if (validNodes.includes(cursor.node.type)) {
         |                                         ^
      22 |       return {
      23 |         selection: focusPath.sourceForNode(),
      24 |         location: focusPath.node.loc,
```

**Comment by lifeart** [comment]
@MichalBryxi `vscode-ember-unstable@1.4.2` released
