### ISSUE TITLE
Can't find components from monorepo addon packages

### ISSUE THREAD

**Issue by sglanzer** [lifeart/ember-language-server#202]
No issue finding other ember addons
![image](https://user-images.githubusercontent.com/31961778/110960475-cc9b8800-831c-11eb-8059-a0b226070100.png)

But can't find components from within monorepo addons
![image](https://user-images.githubusercontent.com/31961778/110960598-e937c000-831c-11eb-82cb-ea84ead60094.png)

Sample monorepo https://github.com/acdn-sglanzer/uels-yarn-workspaces (some extra stuff in there, I just stripped ours down quickly)

**Comment by lifeart** [comment]
logic: https://github.com/lifeart/ember-language-server/blob/component-context-info-origin/src/utils/layout-helpers.ts#L241
tests: https://github.com/lifeart/ember-language-server/blob/component-context-info-origin/test/utils/layout-helpers-test.ts

looks like we have to read "workspaces.packages" from root package.json or find any other way to resolve it

**Comment by sglanzer** [comment]
@lifeart figured out that this was due to lacking re-exports of components in the `app/` directory of the addon.  We were using an automatic re-export at build time.  Swapping to explicit files for the re-export has fixed the discovery issue.  Thanks!
