### ISSUE TITLE
Option to Disable Template Lint Integration

### ISSUE THREAD

**Issue by alexlafroscia** [lifeart/ember-language-server#243]
Is there a way to disable the `ember-template-lint` integration in the langauge server?

I am already running a linter plug-in for `ember-template-lint` that is _much_ more responsive than what `els` provides. It would be nice to have some way to just turn off the `ember-template-lint` integration altogether to avoid running them both!

**Comment by lifeart** [comment]
@alexlafroscia agree, currently its not supported, but quite easy to implement, we could have els.local.templateLintIntegration settings flag for this needs.

**Comment by lifeart** [comment]
Im interesting what caused perf problems, is it quick actions integration? (autofix/ignore rule)

**Comment by alexlafroscia** [comment]
My configuration is for NeoVim, where I use `ale.vim` to run my linting. It have an auto-fix-on-save set up which will very quickly apply Prettier to my `hbs` files.

In my editor, both `ale.vim` and `els` are providing Prettier feedback, duplicating all of the errors I see. When I auto-fix-on-save, `ale.vim` knows immediately that the file is fixed. `els` seems to process the updated, now-correct file almost line by line, where it crawls through a bunch of intermediate error states that the file was never actually in. Yesterday it spent the better part of a minute showing different random errors until things finally settled down and the actual file state matched what `els` was reporting on!

**Comment by lifeart** [comment]
@alexlafroscia thank you for inputs!

**Comment by lifeart** [comment]
`v1.7.0` released with 'els.local.useBuiltinLinting` config option.
Also, linting speed should be improved, if it's possible to get some comparison results - it will be great!

**Comment by alexlafroscia** [comment]
Awesome, thanks!

**Comment by alexlafroscia** [comment]
How do you set configuration options when using the "raw" language server executable, rather than the VSCode extension?

**Comment by lifeart** [comment]
example from tests: <https://github.com/lifeart/ember-language-server/blob/component-context-info-origin/test/test_helpers/integration-helpers.ts#L188> (you have to resolve connection instance and send message to it)

**Comment by alexlafroscia** [comment]
Perfect, thanks!
