### ISSUE TITLE
[Quest] get it working in browser

### ISSUE THREAD

**Issue by lifeart** [lifeart/ember-language-server#305]
Example: https://github.com/microsoft/vscode-extension-samples/tree/main/lsp-web-extension-sample

To do:

- [x] encapsulate FS logic (https://github.com/lifeart/ember-language-server/issues/302)
- [x] upstream worker bundling (https://github.com/lifeart/ember-language-server/pull/306)
- [x] get bundle working in web-worker (https://github.com/lifeart/ember-language-server/pull/316)
- [x] fix 'integration autocomplete works for multiple angle component slots 1' test behavour for async-fs (https://github.com/lifeart/ember-language-server/pull/309)
- [x] fix 'autocomplete works for multiple angle component slots' test behavour for async-fs (https://github.com/lifeart/ember-language-server/pull/309)
- [x] fix 'integration async fs enabled: true Diffent commands handle "els.getLegacyTemplateTokens" command 1' test behavour for async-fs (https://github.com/lifeart/ember-language-server/pull/307, https://github.com/lifeart/ember-language-server/pull/310)
- [x] fix inconsistent project initialization for async fs (https://github.com/lifeart/ember-language-server/pull/308)
- [x] mark change as major (changes server api)
- [x] create walk-async implementation, based on walk-sync

Next steps:

- [x] fix floating 'integration async fs enabled: true Diffent commands handle "els.getLegacyTemplateTokens" command 1' test behavour for async-fs in CI
- [x] prebundle ember-meta-explorer? (updated dependency - https://github.com/lifeart/ember-meta-explorer/commit/62c3d8fa43068ca41fb96962c6332d09515007bf)
- [x] land worker build config from https://github.com/lifeart/vscode-ember/pull/25 (https://github.com/lifeart/ember-language-server/pull/311)
- [x] implement working client (https://github.com/lifeart/vscode-ember/issues/24)

**Comment by NullVoxPopuli** [comment]
related: https://github.com/NullVoxPopuli/limber/issues/325 ;)

**Comment by lifeart** [comment]
![image](https://user-images.githubusercontent.com/1360552/136687738-2e8b2b2d-0e9d-4c0b-9621-6c5c9f42b0b4.png)

finally, able to get it working

**Comment by lifeart** [comment]
closing it as implemented, also uELS 3.0.4 VSCode extension published:

uELS 3.0.4 published to VScode store

<https://marketplace.visualstudio.com/items?itemName=lifeart.vscode-ember-unstable>

Updates:
    * async filesystem access
    * improved startup performance
    * fixed found issues
    * multiple filesystem providers support

New features:
    * experimental VScode web-version support (server bundled to web-worker) <https://code.visualstudio.com/api/extension-guides/web-extensions>
    * sendCommand API for addon authors
    
Improvements:
    * 5x times smaller package size! (10 MB -> 2 MB)
    * faster language client startup time (up to 2x times)
    
Notes:
    * git filesystem is not supported
    * now uELS could be integrated into any browser environment

**Comment by NullVoxPopuli** [comment]
Congrats! This is a very exciting release!
