### ISSUE TITLE
Syntax Error on Argumentless Helper Invocation

### ISSUE THREAD

**Issue by jrjohnson** [lifeart/ember-language-server#319]
I'm attempting to clear up [Invoking Helpers Without Arguments and Parentheses In Named Argument Positions](https://deprecations.emberjs.com/v3.x/%23toc_argument-less-helper-paren-less-invocation) deprecations. In particular patterns in component tests like:

```javscript
await render(hbs`<LeadershipManager
  @removeDirector={{noop}}
  @addDirector={{noop}}
/>`);
```

Using the [noop](https://github.com/DockYard/ember-composable-helpers#noop) helper from ember-composable-helpers to alleviate the need to pass meaningless methods in our tests.

Where the deprecation guide recommends replacing `{{noop}}` with `{{(noop)}}`. With `Unstable Ember Language Server
v3.0.4` enabled VSCode reports 

> Expecting 'ID', 'STRING', 'NUMBER', 'BOOLEAN', 'UNDEFINED', 'NULL', 'DATA', got 'OPEN_SEXPR'glimmer-engine(syntax)

I'm not seeing any problems building or running this test with `ember-source@3.28.0`.

**Comment by lifeart** [comment]
@jrjohnson see https://github.com/lifeart/vscode-ember/issues/23

**Comment by jrjohnson** [comment]
Oh no, I'm sorry. I should have searched a bit harder for this issue. Thanks for being on top of this long before I noticed it! I'll close this now.
