### ISSUE TITLE
integrate a11y addon as builtin

### ISSUE THREAD

**Issue by lifeart** [lifeart/ember-language-server#328]
https://github.com/lifeart/els-a11y-addon

related story: https://github.com/lifeart/ember-language-server/issues/228

**Comment by godric3** [comment]
I took quick look at it and looks like some of functionality works out of the box without addon.
I went to https://github.dev/ember-learn/ember-website, only uELS extension installed, and I got both `role`  and `aria-*` attribute autocomplete. Not sure about part "role attribute autocomplete (**depends on tagName**)", so I'm not sure if it's worth to add this addon as builtin

**Comment by lifeart** [comment]
@godric3 sorry for long delay in response, was on vacation, you are correct!
