### ISSUE TITLE
What's the difference between this fork and the original repo?

### ISSUE THREAD

**Issue by toh995** [lifeart/ember-language-server#348]
Same as title.

I'm just curious what's the difference and why I would choose one over the other. Thanks!

**Comment by lifeart** [comment]
@toh995 original repo is not maintained.

This repo is most feature-complete and tested LS implementation for Ember.

**Comment by lifeart** [comment]
See https://github.com/emberjs/core-notes/blob/cc0bf942be7e79e6a4d2cdc82bebdc1c04be01ae/learning-team/2020-10/2020-10-29.md#follow-up-to-ember-language-server-els-discussion-il-15-min

**Comment by toh995** [comment]
Thanks for the quick answer!
