### ISSUE TITLE
Autocomplete support for `key` argument of `{{#each}}` helper

### ISSUE THREAD

**Issue by bertdeblock** [lifeart/ember-language-server#363]
```hbs
{{#each (array 1 2 3 4 5) key="@identity" as |number|}}
  {{number}}
{{/each}}
```

The `key` argument accepts two fixed special values: `@index` and `@identity`.
I think it would be nice if this could be autocompleted.

**Comment by lifeart** [comment]
Hi @bertdeblock! Thank you for request and sorry for delay.

This feature will be available in uELS `3.0.22`.

There is some limitations:

Autocomplete works fine only for valid hbs syntax.
