### ISSUE TITLE
monorepo template lint support

### ISSUE THREAD

**Issue by bartocc** [lifeart/ember-language-server#374]
I might be wrong, but it looks like template linting does not work when using a monorepo setup.

@lifeart, are you aware of this?

**Comment by lifeart** [comment]
Hi @bartocc! Thank you for report, there is some prev issues, related to monorepo:

https://github.com/lifeart/ember-language-server/issues/168

Do you mind create a "sample/minimal reproduction" repo to test on it?

**Comment by lifeart** [comment]
Right now we trying to resolve template-lint relatively to project root 
https://github.com/lifeart/ember-language-server/blob/component-context-info-origin/src/template-linter.ts#L243

**Comment by bartocc** [comment]
I'm going to setup a minimal repo reproduction 👍

**Comment by bartocc** [comment]
Here's the demo repo @lifeart 

https://github.com/bartocc/uels-monorepo-lint

**Comment by lifeart** [comment]
Hi @bartocc! Thank you for amazing reproduction! `lifeart.vscode-ember-unstable@3.0.23` published.

**Comment by bartocc** [comment]
Thx @lifeart for your reactivity 🙏

I've just updated to 3.0.23 but something is still wrong. Here's the log output for UELS

<img width="766" alt="Capture d’écran 2022-04-15 à 10 21 44" src="https://user-images.githubusercontent.com/47953/163545638-7381d083-3c50-4f85-999a-ad870374389e.png">

> [Info  - 10:19:52 AM] lazy init enabled, waiting for config from VSCode
> "Initializing Ember Language Server at /private/tmp/uels-monorepo-lint"
> [Info  - 10:19:53 AM] UELS: executeInitializers
> [Info  - 10:19:54 AM] Ember CLI project added at /private/tmp/uels-monorepo-lint/packages/my-app
> [Info  - 10:19:54 AM] /private/tmp/uels-monorepo-lint/packages/my-app: registry initialized in 258ms
> [Info  - 10:19:54 AM] /private/tmp/uels-monorepo-lint/packages/my-app: script registry initialized in 0ms
> [Info  - 10:19:54 AM] my-app registry version mismatch [-1, 0], regenerating...
> [Info  - 10:19:54 AM] my-app registry generated in 0ms, new version: 0
> "Module ember-template-lint not found. Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'find-up' imported from /Users/julien/.vscode/extensions/lifeart.vscode-ember-unstable-3.0.23/node_modules/@lifeart/ember-language-server/dist/bundled/node-server.js"

**Comment by lifeart** [comment]
oops, looks like webpack broke smf

**Comment by lifeart** [comment]
ah, it's still broken for me

**Comment by lifeart** [comment]
@bartocc fixed in `3.0.26`, it's vscode packager dependency trimming issue

**Comment by bartocc** [comment]
Works perfectly here too 👍
