### ISSUE TITLE
Auto-closing `{{#if}}`, `{{#let}}`, `{{#each}}`, etc.

### ISSUE THREAD

**Issue by toh995** [lifeart/ember-language-server#388]
Was this considered before?

It would be nice to have auto-closing for handlebars-specific blocks, for example, if I type `{{#if}}` within a handlebars file, then the closing `{{/if}}`  gets inserted right after. Similar to i.e. VS Code, when you type `<div>`, the closing `</div>` is auto-inserted.

Similar idea for `{{#let}}`, `{{#each}}`, etc.

No pressure to actually implement this, just wanted to share an idea, that's all :)

**Comment by lifeart** [comment]
Hi @toh995! Yep, it's possible, at least for mentioned cases
