### ISSUE TITLE
Neovim LSP Issue

### ISSUE THREAD

**Issue by aw1875** [lifeart/ember-language-server#404]
I apologize in advance if I missed this documented somewhere but I've been having issues getting this language server working with Neovim's LSP. I get a stderr in my LSP logs that says `Error: Cannot find module '@glimmer/env'`. I tried adding @glint/core, @glint/environment-ember-loose, and @glint/template to my global npm installs. I've also tried manually adding '@glimmer/env' and have had no luck.

I've also tried this with a few different LSP setups. My most current one uses [lsp-zero](https://github.com/VonHeikemen/lsp-zero.nvim) to configure the server that I installed using Mason:

```lua
local lsp = require('lsp-zero').preset({})

-- ... other setup

lsp.configure('ember', {
    cmd = { "ember-language-server", "--stdio" },
    filetypes = { "handlebars", "typescript", "javascript" },
    on_attach = on_attach,    -- Points to an on_attach function
    capabilities = capabilities    -- Points to a capabilities function
})
```

Also, in case it is helpful this is the entire line from the log file:
```
[ERROR][2023-05-02 15:42:27] .../vim/lsp/rpc.lua:734	"rpc"	"ember-language-server"	"stderr"	"node:internal/modules/cjs/loader:998\n  throw err;\n  ^\n\nError: Cannot find module '@glimmer/env'\nRequire stack:\n- /home/aw1875/.local/share/nvim/mason/packages/ember-language-server/node_modules/@lifeart/ember-language-server/node_modules/@glimmer/syntax/dist/commonjs/es2017/lib/source/source.js\n- /home/aw1875/.local/share/nvim/mason/packages/ember-language-server/node_modules/@lifeart/ember-language-server/node_modules/@glimmer/syntax/dist/commonjs/es2017/index.js\n- /home/aw1875/.local/share/nvim/mason/packages/ember-language-server/node_modules/@lifeart/ember-language-server/lib/utils/template-tokens-collector.js\n- /home/aw1875/.local/share/nvim/mason/packages/ember-language-server/node_modules/@lifeart/ember-language-server/lib/utils/usages-api.js\n- /home/aw1875/.local/share/nvim/mason/packages/ember-language-server/node_modules/@lifeart/ember-language-server/lib/utils/registry-api.js\n- /home/aw1875/.local/share/nvim/mason/packages/ember-language-server/node_modules/@lifeart/ember-language-server/lib/project.js\n- /home/aw1875/.local/share/nvim/mason/packages/ember-language-server/node_modules/@lifeart/ember-language-server/lib/index.js\n- /home/aw1875/.local/share/nvim/mason/packages/ember-language-server/node_modules/@lifeart/ember-language-server/lib/start-server.js\n- /home/aw1875/.local/share/nvim/mason/packages/ember-language-server/node_modules/@lifeart/ember-language-server/bin/ember-language-server.js\n    at Module._resolveFilename (node:internal/modules/cjs/loader:995:15)\n    at Module._load (node:internal/modules/cjs/loader:841:27)\n    at Module.require (node:internal/modules/cjs/loader:1061:19)\n    at require (node:internal/modules/cjs/helpers:103:18)\n    at Object.<anonymous> (/home/aw1875/.local/share/nvim/mason/packages/ember-language-server/node_modules/@lifeart/ember-language-server/node_modules/@glimmer/syntax/dist/commonjs/es2017/lib/source/source.js:8:12)\n    at Module._compile (node:internal/modules/cjs/loader:1159:14)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)\n    at Module.load (node:internal/modules/cjs/loader:1037:32)\n    at Module._load (node:internal/modules/cjs/loader:878:12)\n    at Module.require (node:internal/modules/cjs/loader:1061:19) {\n  code: 'MODULE_NOT_FOUND',\n  requireStack: [\n    '/home/aw1875/.local/share/nvim/mason/packages/ember-language-server/node_modules/@lifeart/ember-language-server/node_modules/@glimmer/syntax/dist/commonjs/es2017/lib/source/source.js',\n    '/home/aw1875/.local/share/nvim/mason/packages/ember-language-server/node_modules/@lifeart/ember-language-server/node_modules/@glimmer/syntax/dist/commonjs/es2017/index.js',\n    '/home/aw1875/.local/share/nvim/mason/packages/ember-language-server/node_modules/@lifeart/ember-language-server/lib/utils/template-tokens-collector.js',\n    '/home/aw1875/.local/share/nvim/mason/packages/ember-language-server/node_modules/@lifeart/ember-language-server/lib/utils/usages-api.js',\n    '/home/aw1875/.local/share/nvim/mason/packages/ember-language-server/node_modules/@lifeart/ember-language-server/lib/utils/registry-api.js',\n    '/home/aw1875/.local/share/nvim/mason/packages/ember-language-server/node_modules/@lifeart/ember-language-server/lib/project.js',\n    '/home/aw1875/.local/share/nvim/mason/packages/ember-language-server/node_modules/@lifeart/ember-language-server/lib/index.js',\n    '/home/aw1875/.local/share/nvim/mason/packages/ember-language-server/node_modules/@lifeart/ember-language-server/lib/start-server.js',\n    '/home/aw1875/.local/share/nvim/mason/packages/ember-language-server/node_modules/@lifeart/ember-language-server/bin/ember-language-server.js'\n  ]\n}\n\nNode.js v18.12.1\n"
```

**Comment by lifeart** [comment]
Hey @aw1875! Thank you for question! You could check https://github.com/NullVoxPopuli/coc-ember for references (it uses this repo as LS).

cc @NullVoxPopuli

**Comment by lifeart** [comment]
Note, if you trying to get ‘glint’ working, you may need to refer to glint repo itself (https://github.com/typed-ember/glint), or install “glint adapter for ember language server” (https://github.com/lifeart/els-addon-glint) *may not work with latest releases

**Comment by aw1875** [comment]
> Hey @aw1875! Thank you for question! You could check https://github.com/NullVoxPopuli/coc-ember for references (it uses this repo as LS).
> 
> cc @NullVoxPopuli

Thanks! Appreciate the reference, I'll take a look through the code.

**Comment by aw1875** [comment]
Just want to also note, if I run the bin directly located at:
````/home/aw1875/.local/share/nvim/mason/packages/ember-language-server/node_modules/.bin/ember-language-server````
which points to the js file at:
```/home/aw1875/.local/share/nvim/mason/packages/ember-language-server/node_modules/@lifeart/ember-language-server/bin```

this is the stack trace I get (just in case I'm actually missing something else):

```
node:internal/modules/cjs/loader:998
  throw err;
  ^

Error: Cannot find module '@glimmer/env'
Require stack:
- /home/aw1875/.local/share/nvim/mason/packages/ember-language-server/node_modules/@lifeart/ember-language-server/node_modules/@glimmer/syntax/dist/commonjs/es2017/lib/source/source.js
- /home/aw1875/.local/share/nvim/mason/packages/ember-language-server/node_modules/@lifeart/ember-language-server/node_modules/@glimmer/syntax/dist/commonjs/es2017/index.js
- /home/aw1875/.local/share/nvim/mason/packages/ember-language-server/node_modules/@lifeart/ember-language-server/lib/utils/template-tokens-collector.js
- /home/aw1875/.local/share/nvim/mason/packages/ember-language-server/node_modules/@lifeart/ember-language-server/lib/utils/usages-api.js
- /home/aw1875/.local/share/nvim/mason/packages/ember-language-server/node_modules/@lifeart/ember-language-server/lib/utils/registry-api.js
- /home/aw1875/.local/share/nvim/mason/packages/ember-language-server/node_modules/@lifeart/ember-language-server/lib/project.js
- /home/aw1875/.local/share/nvim/mason/packages/ember-language-server/node_modules/@lifeart/ember-language-server/lib/index.js
- /home/aw1875/.local/share/nvim/mason/packages/ember-language-server/node_modules/@lifeart/ember-language-server/lib/start-server.js
- /home/aw1875/.local/share/nvim/mason/packages/ember-language-server/node_modules/@lifeart/ember-language-server/bin/ember-language-server.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
    at Module._load (node:internal/modules/cjs/loader:841:27)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/home/aw1875/.local/share/nvim/mason/packages/ember-language-server/node_modules/@lifeart/ember-language-server/node_modules/@glimmer/syntax/dist/commonjs/es2017/lib/source/source.js:8:12)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/aw1875/.local/share/nvim/mason/packages/ember-language-server/node_modules/@lifeart/ember-language-server/node_modules/@glimmer/syntax/dist/commonjs/es2017/lib/source/source.js',
    '/home/aw1875/.local/share/nvim/mason/packages/ember-language-server/node_modules/@lifeart/ember-language-server/node_modules/@glimmer/syntax/dist/commonjs/es2017/index.js',
    '/home/aw1875/.local/share/nvim/mason/packages/ember-language-server/node_modules/@lifeart/ember-language-server/lib/utils/template-tokens-collector.js',
    '/home/aw1875/.local/share/nvim/mason/packages/ember-language-server/node_modules/@lifeart/ember-language-server/lib/utils/usages-api.js',
    '/home/aw1875/.local/share/nvim/mason/packages/ember-language-server/node_modules/@lifeart/ember-language-server/lib/utils/registry-api.js',
    '/home/aw1875/.local/share/nvim/mason/packages/ember-language-server/node_modules/@lifeart/ember-language-server/lib/project.js',
    '/home/aw1875/.local/share/nvim/mason/packages/ember-language-server/node_modules/@lifeart/ember-language-server/lib/index.js',
    '/home/aw1875/.local/share/nvim/mason/packages/ember-language-server/node_modules/@lifeart/ember-language-server/lib/start-server.js',
    '/home/aw1875/.local/share/nvim/mason/packages/ember-language-server/node_modules/@lifeart/ember-language-server/bin/ember-language-server.js'
  ]
}
```

**Comment by aw1875** [comment]
Wanted to delete that last message as it seems like deleting it all and then reinstalling the language server seemed to fix that stack trace. I did however notice that although the language server seems to be running now, I don't notice that it seems to be showing any sort of autocomplete (diagnostics seem to work perfectly now though!). I modified my LSP to point to the correct package now so not sure if I'm missing something else:

```lua
lsp.configure('ember', {
    cmd = {
        "/home/aw1875/.local/share/nvim/mason/packages/ember-language-server/node_modules/.bin/ember-language-server",
        "--stdio" },
    filetypes = { "handlebars", "typescript", "javascript" },
    on_attach = on_attach,
    capabilities = capabilities
})
```

**Comment by NullVoxPopuli** [comment]
if you use mason, and have ember-language-server available as a global bin, it should work.
configuration entry/alias is here: https://github.com/williamboman/mason-lspconfig.nvim/blob/main/lua/mason-lspconfig/mappings/server.lua#L44

**Comment by aw1875** [comment]
@NullVoxPopuli Yeah the language server seems to be running properly after reinstalling it as shown when checking the LSP Info:

```
 2 client(s) attached to this buffer: 
 
 Client: glint (id: 1, bufnr: [1])
 	filetypes:       html.handlebars, handlebars, typescript, typescript.glimmer, javascript, javascript.glimmer
 	autostart:       true
 	root directory:  /home/aw1875/Documents/dev/Learning Ember/emberjs-tutorial
 	cmd:             glint-language-server
 
 Client: ember (id: 2, bufnr: [1])
 	filetypes:       handlebars, typescript, javascript
 	autostart:       true
 	root directory:  /home/aw1875/Documents/dev/Learning Ember/emberjs-tutorial
 	cmd:             ember-language-server --stdio

```

But it seems like the only info showing up in my autocomplete is text from the buffer (which makes me think I'm still missing something)
![image](https://user-images.githubusercontent.com/4970015/235808970-09b021f0-a91d-4433-8392-73ec7a3274d8.png)

**Comment by NullVoxPopuli** [comment]
what does the command `set filetype?` return?

this is what I see:
![image](https://user-images.githubusercontent.com/199018/235811710-04f47bf1-1ac9-499a-89a1-5ed8a28230ba.png)

```
:set filetype?<CR>
  filetype=handlebars
```

**Comment by aw1875** [comment]
It returns the same thing (filetype=handlebars). Also I apologize for these questions, I'm new to working with ember and was trying to follow the documentation they had on their website for working with it in vim.

**Comment by NullVoxPopuli** [comment]
no worries!! I wrote the stuff for (neo)vim on the site, so any issues you have are appropriate to ask!

also greatest welcomes!!!! :tada: 


fwiw -- all this manual LSP setup stuff is quite cumbersome :sweat_smile: 

I have a whole folder of LSP configs: https://github.com/NullVoxPopuli/dotfiles/tree/main/home/.config/nvim/lua/plugin-config/lsp

**Comment by aw1875** [comment]
Thank you! I was actually looking through your configs earlier as I had seen your name pop up a few times in this process. I'll try diving deeper into those and see if I can get it all working properly. I'm actually going to revert my lsp back to use lspconfig instead of lsp-zero which should make this process a little easier

**Comment by aw1875** [comment]
I just marked this as closed as I feel like it seems like its _technically_ working correctly. As you can see (I'm currently going through the ember quickstart tutorial) it does show the class as expected:

![image](https://user-images.githubusercontent.com/4970015/236070833-53398d29-bca0-4fee-b856-d9c4aa100170.png)

I think I was just confused as I was expecting to have it show things for something like `#each` or `@model`. I also noticed that it doesn't format if I use `:lua vim.lsp.buf.format()` command, instead it gives this error:

```
[LSP] Format request failed, no matching language servers.
```

Again, it seems like it works as expected, I just thought it was missing those few things noted.

**Comment by NullVoxPopuli** [comment]
yeah, formatting is only done via prettier atm, can be setup like this: https://github.com/NullVoxPopuli/dotfiles/blob/main/home/.config/nvim/lua/plugin-config/lsp/integrations.lua#L51

here is the key: https://github.com/NullVoxPopuli/dotfiles/blob/main/home/.config/nvim/lua/plugin-config/lsp/integrations.lua#L28

I hope one day, this is built in to neovim :sweat_smile: 

>  like #each or @model

yeah, this def sounds like something this language server could provide -- though -- does it suggest these things in vscode?

**Comment by aw1875** [comment]
> yeah, formatting is only done via prettier atm, can be setup like this: https://github.com/NullVoxPopuli/dotfiles/blob/main/home/.config/nvim/lua/plugin-config/lsp/integrations.lua#L51

ya I actually run neoformat for any prettier compliant files and then the default nvim lsp formatting for every other file.

> yeah, this def sounds like something this language server could provide -- though -- does it suggest these things in vscode?

I just downloaded vscode and the extensions to check and it looks like it does. It also suggests things like `ul` and `li` in this example which I also noticed doesn't come up in neovim

**Comment by NullVoxPopuli** [comment]
is there any way to see which vscode extension is providing which suggestions?

**Comment by aw1875** [comment]
For the `#each` tag it just says ember. I'm assuming the `ul` and `li` are just coming from vscode somewhere else.
