### ISSUE TITLE
Angle brackets autocomplete lil bug

### ISSUE THREAD

**Issue by betocantu93** [lifeart/ember-language-server#42]
Hello, great extension, thanks, I found this little bug.

I have this component 
```hbs
{{tables/i18n-models-table}}
```
The angle brackets equivalent is 
```hbs
<Tables::I18nModelsTable />
```
And the extension autocompletes with the n after the 18, upper case, like this: 
```hbs
<Tables::I18NModelsTable />
```

**Comment by lifeart** [comment]
looks like 
```js
'tables/i18n-models-table'.split('/').map((el)=>{ 
   return el.split('-').map(el=>{ 
     return _.capitalize(el) 
  }).join('') 
}).join('::');
``` 
should work

also:

https://github.com/ember-codemods/ember-angle-brackets-codemod/blob/master/transforms/angle-brackets/transform.js#L40

one more: https://github.com/emberjs/ember-inspector/blob/47138779d4f6c559bda90a0e53df5838ac6da446/ember_debug/libs/view-inspection.js#L489


"serialization" from :

https://github.com/rwjblue/ember-angle-bracket-invocation-polyfill/blob/master/lib/ast-transform.js#L33


```js
function dasherize(string) {
	const ALPHA = /[A-Za-z]/;

  return string.replace(/[A-Z]/g, function(char, index) {
	if (index === 0 || !ALPHA.test(string[index - 1])) {
	  return char.toLowerCase();
	}

	return `-${char.toLowerCase()}`;
  });
}

function replaceNestedComponents(string) {
  return string.replace(/::/g, '/');
}


function serializeComponentName(name) {
	return replaceNestedComponents(dasherize(name));
}

```

**Comment by lifeart** [comment]
@betocantu93 fixed in `lifeart.vscode-ember-unstable@0.2.58`
