### ISSUE TITLE
"Symbol" support for .gjs / .gts files

### ISSUE THREAD

**Issue by Windvis** [lifeart/ember-language-server#420]
When converting a component to .gjs I noticed that I lost the ability to easily rename symbols (in both .js and .hbs code) in VS Code (F2).

Is this something that the language server provides or is that a different extension?

**Comment by lifeart** [comment]
Hi @Windvis, thank you for report! Could you re-check with disabled `glint` extension?

**Comment by Windvis** [comment]
We're not using glint yet in this project. The only Ember related extensions I have installed in VSCode is the [extension pack](https://marketplace.visualstudio.com/items?itemName=EmberTooling.emberjs).

So it sounds like this is supposed to work already and it's an issue in my setup?

**Comment by lifeart** [comment]
In this case, it looks like a think to improve from `ls` side, because at the moment we does not have symbol provider for `gts/gjs` in codebase. 

<img width="1004" alt="image" src="https://github.com/lifeart/ember-language-server/assets/1360552/53c70ca3-733a-4958-8daa-f77d0a50547d">

**Comment by Windvis** [comment]
I think the symbol provider would also enable the "outline view" and "go to definition" features in VS Code so that would be very nice to have, especially in larger .gts / .gjs files.

**Comment by Windvis** [comment]
Closing again, since this isn't the main fork anymore.
