### ISSUE TITLE
`.gjs` VS Code codelens support

### ISSUE THREAD

**Issue by Windvis** [lifeart/ember-language-server#421]
It seems that .gjs files don't display the (very useful!) codelenses on top of the page that made it easy to switch between all related files. It's not a huge problem since the template and js are now part of a single file, but I think it could still be nice to easily switch to the related test file (or the app reexport for v1 addon components)?

**Comment by Windvis** [comment]
Sorry, wrong repo, I assumed this was a monorepo that included all the consumers.

**Comment by lifeart** [comment]
Hi @Windvis, no worries!
In general, we should support `.gjs` on `ls` level in `els.getRelatedFiles` command.
