### ISSUE TITLE
Property 'args' does not exist on type 'Template'

### ISSUE THREAD

**Issue by blmundie** [lifeart/ember-language-server#63]
I'm getting the error "Property 'args' does not exist on type 'Template'" when using `@argumentName` in my templates.  I reinstalled the extension and still get it.

**Comment by lifeart** [comment]
Hi @blmundie! Thank you for issue, looks like you have https://github.com/lifeart/els-addon-typed-templates installed. could you provide minimal reproduction repo for such issue? Do you have template-only component? 

if you have `els-addon-typed-templates` check it's version, likely it's outdated.

**Comment by lifeart** [comment]
could you send logs from this window?

![image](https://user-images.githubusercontent.com/1360552/73977105-c0374580-493a-11ea-8f6b-e6d4a9bc9ea9.png)

**Comment by blmundie** [comment]
I have `"els-addon-typed-templates": "^2.2.11",`

I created a test component with only `{{@testArgument}}` in the template as a basic example.  The output is.

```
[Info  - 5:08:17 PM] Ember CLI project added at /home/bryan/code/httscada_frontend
[Info  - 5:08:17 PM] /home/bryan/code/httscada_frontend: registry initialized in 357ms
[Info  - 5:08:17 PM] /home/bryan/code/httscada_frontend: script registry initialized in 3ms
[Info  - 5:08:17 PM] --------------------
[Info  - 5:08:17 PM] loded language server addons:
[Info  - 5:08:17 PM]     addon: els-addon-typed-templates
[Info  - 5:08:17 PM] --------------------
===============
import Component from "./component";

import { GlobalRegistry } from "ember-typed-templates";

interface TemplateScopeRegistry {

}

type Modify<T, R> = Omit<T, keyof R> & R;

type EmberTemplateScopeRegistry = Modify<TemplateScopeRegistry, GlobalRegistry>;



export default class Template extends Component {
  
  globalScope:  EmberTemplateScopeRegistry;
  defaultYield() {
    return [];
  }
  //@mark-meaningful-issues-start
  
  //@mark [1,0:1,17]
  "1,0:1,17 - MustacheStatement"() { return this["1,2:1,15 - PathExpression"](); /*@path-mark 1,0:1,17*/};

  //@mark [1,2:1,15]
  "1,2:1,15 - PathExpression"() { return this.args.testArgument; /*@path-mark 1,2:1,15*/};
}
===============
```

**Comment by lifeart** [comment]
@blmundie could you provide component `js` code?

Looks like compiled template extended from component without args property in constructor.
It's definetly `typed-templates` addon issue, and I'm trying to clarify details to figure out `stable` fix.

as shor-term fix you can skip typescript template / property linting using this readme part: (https://github.com/lifeart/els-addon-typed-templates#ignore-line)
![image](https://user-images.githubusercontent.com/1360552/73986251-3002fb80-494e-11ea-8ba5-effe632415b2.png)

**Comment by blmundie** [comment]
I do have a component that inherits form another component which then causes all templates to have errors.  I can setup an example repo Monday.  It could be that the way I'm doing the inheritance isn't correct, but what I have is basically the following.

```
import Component from '@glimmer/component';

export interface ParentComponentArgs {
    baseArg: boolean
}

export default class ParentComponent<Args extends ParentComponentArgs> extends Component<Args>  {
}

export interface ChildComponentArgs extends ParentComponentArgs {
    childArg: boolean
}

export default class ChildComponent extends ParentComponent<ChildComponentArgs>  {
}
```

**Comment by lifeart** [comment]
looks like it's dependency deph lookup limitation, https://github.com/lifeart/els-addon-typed-templates/blob/master/src/lib/hbs-converter.ts#L102 (by default - depth = +1 level)

could you change it to 10 in compiled code and relaunch vs code? 

try https://github.com/lifeart/els-addon-typed-templates/releases/tag/v2.2.12
`els-addon-typed-templates@2.2.12`

**Comment by blmundie** [comment]
Upgrading to 2.2.12 fixed it.  Thanks for the help.  Great project.
