### ISSUE TITLE
Falsy linting error in VS Code editor

### ISSUE THREAD

**Issue by nightire** [lifeart/ember-language-server#70]
## Description

This error only reproduces after performing the following steps:

1. Create an ember octane application. (using ember-cli@3.16.0)
2. remove `ember-cli-template-lint` and install `ember-template-lint`.
3. change `extends: 'octane'` to `extends: ['octane', 'stylistic']` in `.template-lintrc.js`
4. remove `ember-cli-eslint` and install `eslint`
5. now open a `.js` or `.hbs` file, change anything and save, should see the following:

![image](https://user-images.githubusercontent.com/1104018/75845051-dc7fb280-5e12-11ea-8ef8-592a9346904d.png)

and as the screenshot shows, execute linting in the command line won't detect any real errors, it's only happening in the editor.

## Reproduction Repository

https://github.com/nightire/vscode-linting-error

## Environments

- ember-cli version: v3.6.0
- ember.js version: ~3.16.0
- node version: v12.14.1
- ember-language-server version: v0.3.8

**Comment by lifeart** [comment]
fixed in `UELS@1.0.0`
